
import React from 'react';

interface Props {
  content: string;
}

export const MarkdownRenderer: React.FC<Props> = ({ content }) => {
  // Simple heuristic parsing for basic markdown elements generated by Gemini
  const parseContent = (text: string) => {
    return text.split('\n').map((line, idx) => {
      // Headers
      if (line.startsWith('### ')) return <h3 key={idx} className="text-xl font-bold mt-4 mb-2 text-indigo-700">{line.replace('### ', '')}</h3>;
      if (line.startsWith('## ')) return <h2 key={idx} className="text-2xl font-bold mt-6 mb-3 text-indigo-800 border-b pb-2">{line.replace('## ', '')}</h2>;
      if (line.startsWith('# ')) return <h1 key={idx} className="text-3xl font-extrabold mt-8 mb-4 text-indigo-900">{line.replace('# ', '')}</h1>;
      
      // Tables (Simplified)
      if (line.startsWith('|')) {
         // This is a crude table renderer, in a real app we'd use a markdown library.
         // For the prompt's 3-column table requirement, we'll try to detect the header and rows.
         return <div key={idx} className="bg-gray-50 border px-4 py-2 font-mono text-sm overflow-x-auto whitespace-nowrap">{line}</div>;
      }

      // Bold
      const boldLine = line.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>');
      
      // Lists
      if (line.trim().startsWith('- ') || line.trim().startsWith('* ')) {
        return <li key={idx} className="ml-6 list-disc mb-1" dangerouslySetInnerHTML={{ __html: boldLine.replace(/^[-*]\s/, '') }} />;
      }
      if (/^\d+\./.test(line.trim())) {
        return <li key={idx} className="ml-6 list-decimal mb-1" dangerouslySetInnerHTML={{ __html: boldLine.replace(/^\d+\.\s/, '') }} />;
      }

      return <p key={idx} className="mb-2 leading-relaxed" dangerouslySetInnerHTML={{ __html: boldLine }} />;
    });
  };

  return <div className="prose max-w-none text-gray-800">{parseContent(content)}</div>;
};
